#!/bin/bash
cd /deploy/backend || exit 2

AWS_DEFAULT_REGION="us-east-1"
export AWS_DEFAULT_REGION

DJANGO_SETTINGS_MODULE='conduit.settings.ec2'
export DJANGO_SETTINGS_MODULE

pipenv run gunicorn --config ../infrastructure/aws/codedeploy/gunicorn.ec2.conf conduit.wsgi
